### ISSUE TITLE
EntityMetadata updates

### ISSUE THREAD

**Issue by JasperLorelai** [Xezard/XGlow#3]
I find that the changes introduced by [this commit](https://github.com/Xezard/XGlow/commit/284ad935205d075a558282b6f2ef389e131ccd24) (v1.0.4) completely break the fixes introduced in [this commit](https://github.com/Xezard/XGlow/commit/7dda776e04345cfe047c36c13d3bfa4aee6afb2c) (v1.0.3).

Another issue I noticed is that 1.0.3 only partly fixes glow reset on metadata changes.

Perhaps the intended fixes for 1.0.4 would work in combination with the fixes in 1.0.3? I don't know - haven't tested it myself.

**Comment by Xezard** [comment]
I made some mistakes by making [this commit](https://github.com/Xezard/XGlow/commit/7dda776e04345cfe047c36c13d3bfa4aee6afb2c) without checking the entire plugin to the end, because later it turned out that the entity's glow is interrupted if the entity, for example, is on fire.  Which essentially meant that the packetlistener didn't work the way I expected it to work. Later I released [this commit](https://github.com/Xezard/XGlow/commit/284ad935205d075a558282b6f2ef389e131ccd24), which I fully tested and it worked correctly on Yatopia-"7f24790" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT).

Anyway, I'll try to double-check the plugin as soon as possible.

**Comment by JasperLorelai** [comment]
I think it's important to note that I was using no update period (0) and a single color. Any alternative settings might mess with the tests.

**Comment by Xezard** [comment]
Published a new [release](https://github.com/Xezard/XGlow/releases/tag/1.0.5) based on a commit with a supposed fix for this issue. If you have the option - check XGlow v1.0.5 and report if the problem has been fixed.

**Comment by JasperLorelai** [comment]
Yeah, I'm not getting anywhere with this... I tried debugging further after your commit, but could not find anything causing the issue. The last thing I did was try was using git-Yatopia-"99e3c5d" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT).

The glow effect always has a lifetime of a single tick. The only way I could produce a stable result is by using an update interval of 1 and listing a color twice - an animation.

Before Yatopia I was using git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) with ProtocolLib v4.5.1. Aside from mainly testing a separate piece of code, using your example produced the very same results.

**Comment by Xezard** [comment]
![XGlow test](https://user-images.githubusercontent.com/17483454/105492882-0d3e3400-5cd2-11eb-954b-e5d3648047ab.gif)
XGlow v.1.0.5, XGlowExample v.1.0.5, ProtocolLib v.4.5.1
Glow object:
```java
Glow.builder()
    .animatedColor(ChatColor.AQUA)
    .name("test")
    .build();
```

Tested on Yatopia 1.16.5 and its works perfectly.
